-- org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.HSQLDBDelegate

DROP TABLE IF EXISTS QRTZ_TRACK_ITERATIONS;
DROP TABLE IF EXISTS QRTZ_TRACK_JOB_DETAILS;

CREATE TABLE QRTZ_TRACK_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
RESTARTED_UID VARCHAR(50) NULL,
DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE BOOLEAN NOT NULL,
IS_NONCONCURRENT BOOLEAN NOT NULL,
IS_UPDATE_DATA BOOLEAN NOT NULL,
REQUESTS_RECOVERY BOOLEAN NOT NULL,
JOB_DATA BLOB NULL,
RESULT BLOB NULL,
RETURN_CODE VARCHAR(120) NULL,
TIME_END TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID))
;

CREATE TABLE QRTZ_TRACK_ITERATIONS (
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
ITERID VARCHAR(50) NULL,
SUCCESS BOOLEAN DEFAULT FALSE NOT NULL, 
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID))
;
