/* org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.SybaseDelegate */

use your_db_name_here
go

IF OBJECT_ID('QRTZ_TRACK_ITERATIONS') IS NOT NULL 
delete from QRTZ_TRACK_ITERATIONS
go
IF OBJECT_ID('QRTZ_TRACK_JOB_DETAILS') IS NOT NULL 
delete from QRTZ_TRACK_JOB_DETAILS
go

drop table QRTZ_TRACK_ITERATIONS
go
drop table QRTZ_TRACK_JOB_DETAILS
go

CREATE TABLE QRTZ_TRACK_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
RESTARTED_UID VARCHAR(50) NULL,
DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE bit NOT NULL,
IS_NONCONCURRENT bit NOT NULL,
IS_UPDATE_DATA bit NOT NULL,
REQUESTS_RECOVERY bit NOT NULL,
JOB_DATA image NULL,
RESULT image NULL,
RETURN_CODE VARCHAR(120) NULL,
TIME_END TIMESTAMP DEFAULT CURRENT_TIMESTAMP # todo verify
)
go

CREATE TABLE QRTZ_TRACK_ITERATIONS (
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
ITERID VARCHAR(50) NULL,
SUCCESS BOOLEAN NOT NULL DEFAULT FALSE # todo verify 
)
go

alter table QRTZ_TRACK_JOB_DETAILS
add constraint PK_qrtz_track_job_details primary key clustered (SCHED_NAME,JOB_NAME,JOB_GROUP,UID)
go
alter table QRTZ_TRACK_ITERATIONS
add constraint PK_qrtz_track_iterations primary key clustered (SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID)
go


