#DROP TABLE IF EXISTS QRTZ_TRACK_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRACK_ITERATIONS;
DROP TABLE IF EXISTS QRTZ_TRACK_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRACK_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRACK_JOB_DETAILS;

CREATE TABLE QRTZ_TRACK_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,

UID VARCHAR(50) NOT NULL,

DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE VARCHAR(1) NOT NULL,
IS_NONCONCURRENT VARCHAR(1) NOT NULL,
IS_UPDATE_DATA VARCHAR(1) NOT NULL,
REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
JOB_DATA BLOB NULL,
RESULT BLOB NULL,
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID))
;

CREATE TABLE QRTZ_TRACK_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,

UID VARCHAR(50) NOT NULL,

JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(250) NULL,
NEXT_FIRE_TIME BIGINT(13) NULL,
PREV_FIRE_TIME BIGINT(13) NULL,
PRIORITY INTEGER NULL,
TRIGGER_STATE VARCHAR(16) NOT NULL,
TRIGGER_TYPE VARCHAR(8) NOT NULL,
START_TIME BIGINT(13) NOT NULL,
END_TIME BIGINT(13) NULL,
CALENDAR_NAME VARCHAR(200) NULL,
MISFIRE_INSTR SMALLINT(2) NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID),
INDEX (SCHED_NAME,JOB_NAME,JOB_GROUP,UID),
FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID)
REFERENCES QRTZ_TRACK_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP,UID))
;

#CREATE TABLE QRTZ_TRACK_SIMPLE_TRIGGERS (
#SCHED_NAME VARCHAR(120) NOT NULL,
#TRIGGER_NAME VARCHAR(200) NOT NULL,
#TRIGGER_GROUP VARCHAR(200) NOT NULL,

#UID VARCHAR(50) NOT NULL,

#REPEAT_COUNT BIGINT(7) NOT NULL,
#REPEAT_INTERVAL BIGINT(12) NOT NULL,
#TIMES_TRIGGERED BIGINT(10) NOT NULL,
#PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID),
#INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP,UID),
#FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID)
#REFERENCES QRTZ_TRACK_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID))
#;

CREATE TABLE QRTZ_TRACK_BLOB_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(200) NOT NULL,
TRIGGER_GROUP VARCHAR(200) NOT NULL,

UID VARCHAR(50) NOT NULL,

BLOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID),
INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP,UID),
FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID)
REFERENCES QRTZ_TRACK_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,UID))
;

CREATE TABLE QRTZ_TRACK_ITERATIONS (
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
ITERID VARCHAR(50) NULL,
SUCCESS BOOLEAN NOT NULL DEFAULT FALSE, 
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID),
INDEX (SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID))
;
commit;   
