DELETE FROM QRTZ_TRACK_ITERATIONS;
DELETE FROM QRTZ_TRACK_JOB_DETAILS;

DROP TABLE QRTZ_TRACK_ITERATIONS;
DROP TABLE QRTZ_TRACK_JOB_DETAILS;

CREATE TABLE QRTZ_TRACK_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
RESTARTED_UID VARCHAR(50) NULL,
DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE VARCHAR2(1) NOT NULL,
IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
JOB_DATA BLOB NULL,
RESULT BLOB NULL,
RETURN_CODE VARCHAR(120) NULL,
TIME_END TIMESTAMP DEFAULT CURRENT_TIMESTAMP, # todo verify
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID))
;

CREATE TABLE QRTZ_TRACK_ITERATIONS (
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
UID VARCHAR(50) NOT NULL,
ITERID VARCHAR(50) NULL,
SUCCESS BOOLEAN NOT NULL DEFAULT FALSE, # todo verify
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID))
;

create index idx_qrtz_track_iterations on qrtz_track_iterations(SCHED_NAME,JOB_NAME,JOB_GROUP,UID,ITERID);

commit;   
