/*
 *     ParallelJ, framework for parallel computing
 *
 *     Copyright (C) 2010, 2011, 2012 Atos Worldline or third-party contributors as
 *     indicated by the @author tags or express copyright attribution
 *     statements applied by the authors.
 *
 *     This library is free software; you can redistribute it and/or
 *     modify it under the terms of the GNU Lesser General Public
 *     License as published by the Free Software Foundation; either
 *     version 2.1 of the License.
 *
 *     This library is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *     Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public
 *     License along with this library; if not, write to the Free Software
 *     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.24 at 04:10:38 PM CET 
//


package org.parallelj.internal.conf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parallelj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Configuration_QNAME = new QName("parallelj", "configuration");
    private final static QName _Procedures_QNAME = new QName("parallelj", "procedures");
    private final static QName _Servers_QNAME = new QName("parallelj", "servers");
    private final static QName _Beans_QNAME = new QName("parallelj", "beans");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parallelj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CServers.Telnet }
     * 
     */
    public CServers.Telnet createCServersTelnet() {
        return new CServers.Telnet();
    }

    /**
     * Create an instance of {@link CProcedures.Procedure }
     * 
     */
    public CProcedures.Procedure createCProceduresProcedure() {
        return new CProcedures.Procedure();
    }

    /**
     * Create an instance of {@link CProcedures }
     * 
     */
    public CProcedures createCProcedures() {
        return new CProcedures();
    }

    /**
     * Create an instance of {@link ParalleljConfiguration }
     * 
     */
    public ParalleljConfiguration createParalleljConfiguration() {
        return new ParalleljConfiguration();
    }

    /**
     * Create an instance of {@link CBeans }
     * 
     */
    public CBeans createCBeans() {
        return new CBeans();
    }

    /**
     * Create an instance of {@link CServers.Jmx }
     * 
     */
    public CServers.Jmx createCServersJmx() {
        return new CServers.Jmx();
    }

    /**
     * Create an instance of {@link CBeans.Bean }
     * 
     */
    public CBeans.Bean createCBeansBean() {
        return new CBeans.Bean();
    }

    /**
     * Create an instance of {@link CServers }
     * 
     */
    public CServers createCServers() {
        return new CServers();
    }
    
    /**
     * Create an instance of {@link CServers.Telnet }
     * 
     */
    public CServers.Ssh createCServersSsf() {
        return new CServers.Ssh();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParalleljConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "parallelj", name = "configuration")
    public JAXBElement<ParalleljConfiguration> createConfiguration(ParalleljConfiguration value) {
        return new JAXBElement<ParalleljConfiguration>(_Configuration_QNAME, ParalleljConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CProcedures }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "parallelj", name = "procedures")
    public JAXBElement<CProcedures> createProcedures(CProcedures value) {
        return new JAXBElement<CProcedures>(_Procedures_QNAME, CProcedures.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CServers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "parallelj", name = "servers")
    public JAXBElement<CServers> createServers(CServers value) {
        return new JAXBElement<CServers>(_Servers_QNAME, CServers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CBeans }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "parallelj", name = "beans")
    public JAXBElement<CBeans> createBeans(CBeans value) {
        return new JAXBElement<CBeans>(_Beans_QNAME, CBeans.class, null, value);
    }

}
