//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 03:07:54 PM CEST 
//


package org.parallelj.internal.conf.pojos;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CExecutors complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CExecutors">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://parallelj.org}executor-service"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default-service-type" use="required" type="{http://parallelj.org}threadpooltype" />
 *       &lt;attribute name="default-service-class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="default-pool-size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CExecutors", propOrder = {
    "executorService"
})
public class CExecutors {

    @XmlElement(name = "executor-service", required = true)
    protected List<CExecutor> executorService;
    @XmlAttribute(name = "default-service-type", required = true)
    protected Threadpooltype defaultServiceType;
    @XmlAttribute(name = "default-service-class")
    protected String defaultServiceClass;
    @XmlAttribute(name = "default-pool-size")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger defaultPoolSize;


    /**
     * Gets the value of the executorService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executorService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutorService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CExecutor }
     * 
     * 
     */
    public List<CExecutor> getExecutorService() {
        if (executorService == null) {
            executorService = new ArrayList<CExecutor>();
        }
        return this.executorService;
    }

    /**
     * Gets the value of the defaultServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link Threadpooltype }
     *     
     */
    public Threadpooltype getDefaultServiceType() {
        return defaultServiceType;
    }

    /**
     * Sets the value of the defaultServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Threadpooltype }
     *     
     */
    public void setDefaultServiceType(Threadpooltype value) {
        this.defaultServiceType = value;
    }

    /**
     * Gets the value of the defaultServiceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultServiceClass() {
        return defaultServiceClass;
    }

    /**
     * Sets the value of the defaultServiceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultServiceClass(String value) {
        this.defaultServiceClass = value;
    }

    /**
     * Gets the value of the defaultPoolSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefaultPoolSize() {
        return defaultPoolSize;
    }

    /**
     * Sets the value of the defaultPoolSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefaultPoolSize(BigInteger value) {
        this.defaultPoolSize = value;
    }

}
