//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 06:02:02 PM CEST 
//


package org.parallelj.internal.conf.pojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CSsh complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CSsh">
 *   &lt;complexContent>
 *     &lt;extension base="{http://parallelj.org}CServer">
 *       &lt;sequence>
 *         &lt;element ref="{http://parallelj.org}auths"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CSsh", propOrder = {
    "auths"
})
public class CSsh
    extends CServer
{

    @XmlElement(required = true)
    protected CAuths auths;

    /**
     * Gets the value of the auths property.
     * 
     * @return
     *     possible object is
     *     {@link CAuths }
     *     
     */
    public CAuths getAuths() {
        return auths;
    }

    /**
     * Sets the value of the auths property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAuths }
     *     
     */
    public void setAuths(CAuths value) {
        this.auths = value;
    }

}
