//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 03:07:54 PM CEST 
//


package org.parallelj.internal.conf.pojos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for threadpooltype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="threadpooltype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FIXED_THREAD_POOL"/>
 *     &lt;enumeration value="CACHED_THREAD_POOL"/>
 *     &lt;enumeration value="SINGLE_THREAD_EXECUTOR"/>
 *     &lt;enumeration value="PROVIDED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "threadpooltype")
@XmlEnum
public enum Threadpooltype {

    FIXED_THREAD_POOL,
    CACHED_THREAD_POOL,
    SINGLE_THREAD_EXECUTOR,
    PROVIDED;

    public String value() {
        return name();
    }

    public static Threadpooltype fromValue(String v) {
        return valueOf(v);
    }

}
