//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 04:56:09 PM CET 
//


package org.parallelj.tools.conf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParalleljConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParalleljConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{parallelj}procedures"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="parallelj")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParalleljConfiguration", propOrder = {
    "procedures"
})
public class ParalleljConfiguration {

    @XmlElement(required = true)
    protected CProcedures procedures;

    /**
     * Gets the value of the procedures property.
     * 
     * @return
     *     possible object is
     *     {@link CProcedures }
     *     
     */
    public CProcedures getProcedures() {
        return procedures;
    }

    /**
     * Sets the value of the procedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link CProcedures }
     *     
     */
    public void setProcedures(CProcedures value) {
        this.procedures = value;
    }

}
